CREATE TABLE CATEGORIA(
	ID_CATEGORIA INTEGER PRIMARY KEY,
	NOME VARCHAR(50),
	DISPONIVEL BOOLEAN
);
CREATE TABLE PRODUTO(
	ID_PRODUTO INTEGER PRIMARY KEY,
	NOME VARCHAR(50),
	CATEGORIA VARCHAR(50),
	DESCRICAO VARCHAR(1000),
	PRICE NUMERIC(10,2),
	DISPONIVEL BOOLEAN,
	DESTAQUE BOOLEAN,
	DT_CADASTRO DATE DEFAULT CURRENT_DATE,
	ID_CATEGORIA INTEGER,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE COMENTARIO(
	ID_COMENTARIO INTEGER PRIMARY KEY,
	ID_PRODUTO INTEGER,
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	DT_COMENTARIO DATE DEFAULT CURRENT_DATE,
	CLASSIFICACAO NUMERIC(1),
	COMENTARIOS VARCHAR(500),
	EMAIL VARCHAR(50)
);

